installer:
  release: "v0.4.21"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:e5b1ec26-325-9492"
  devtron:
    image: "quay.io/devtron/hyperion:6e7a6b9d-280-9489"
    cicdImage: "quay.io/devtron/devtron:6e7a6b9d-326-9488"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "6e7a6b9d39224adf674b729535b04b5d3cc28bf2"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "6e7a6b9d39224adf674b729535b04b5d3cc28bf2"
